spring:
  application:
    name: notificationservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pozdravliator
    username: postgres
    password: iamdeadlytired795795
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rmuser
    password: rmpassword
    virtual-host: /
    connection-timeout: 5000
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 2000
        multiplier: 2.0
        max-interval: 10000
      default-requeue-rejected: false
  amqp:
    deserialization:
      trust:
        all: true
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: Pavel200-7@yandex.ru
    password: prvepeophfnvnjlm

mail:
  debug: true


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    org.apache.catalina.connector.CoyoteAdapter: DEBUG
    org.apache.catalina.core.StandardEngine: DEBUG

    org.apache.tomcat.util.net: DEBUG
    org.apache.tomcat.util.http: DEBUG